version: "2"
services:
    registry:
      image: demoregistry.dataman-inc.com/library/centos7-docker-registry:v2.5.0.2016090301
      network_mode: host
      restart: always
      privileged: true
      logging:
        driver: journald
      volumes:
        - ../offline-registry_data:/var/lib/registry
        - ./config/registry/:/etc/registry/
      environment:
        - GODEBUG=netdns=cgo
      command:
        ["serve", "/etc/registry/config.yml"]
