version: 0.1
log:
  level: info 
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
http:
    addr: 192.168.1.214:5000
    secret: placeholder
    tls:
      certificate: /etc/registry/ssl/offlineregistry.dataman-inc.com.crt
      key: /etc/registry/ssl/offlineregistry.dataman-inc.com.key
